// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbzfsXEpnXS08HjzUlRScvAFyYSdMH9A4',
    appId: '1:765866363329:web:ab93ae4b5fe7cbb94f0740',
    messagingSenderId: '765866363329',
    projectId: 'fcmtest-7e77a',
    authDomain: 'fcmtest-7e77a.firebaseapp.com',
    storageBucket: 'fcmtest-7e77a.appspot.com',
    measurementId: 'G-4ZXZS1KGWV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFRYwvKaIyT3Wwph4SE2Px_8goqcOljxo',
    appId: '1:765866363329:android:8257f18b51460dd44f0740',
    messagingSenderId: '765866363329',
    projectId: 'fcmtest-7e77a',
    storageBucket: 'fcmtest-7e77a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCv2146qs6hCZmY4BmNtFjF7E0CfA7ffs',
    appId: '1:765866363329:ios:575e29553c7f3c994f0740',
    messagingSenderId: '765866363329',
    projectId: 'fcmtest-7e77a',
    storageBucket: 'fcmtest-7e77a.appspot.com',
    iosClientId: '765866363329-o763nuk88b76t6e952e0d61qjv41a3p3.apps.googleusercontent.com',
    iosBundleId: 'com.aci.ricomsApp1',
  );
}
